---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with API defined in an external Swagger file along with Lambda integrations and CORS configurations
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ../swagger/oshidori-API.yaml
      StageName: Development
      Variables:
        # NOTE: Before using this template, replace the <<region>> and <<account>> fields
        #       in Lambda integration URI in the swagger file to region and accountId 
        #       you are deploying to
        GetFunctionArn: !Ref TasksGetFunction
        PostFunctionArn: !Ref TasksPostFunction
  TasksGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://oshidori-dev-hosting/index.js.zip
      Handler: index.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /tasks
            Method: GET
  TasksPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://oshidori-dev-hosting/index.js.zip
      Handler: index.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /tasks
            Method: POST     
  Table:
    Type: AWS::Serverless::SimpleTable      
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Development'


